operator: 
  name: inpainting
  sigma_noise: 0.05      # measurement noise level

model: 
  sigma_min: 0.002
  sigma_max: 100.
  url: https://nvlabs-fi-cdn.nvidia.com/edm/pretrained/edm-ffhq-64x64-uncond-vp.pkl
  device: cuda

mask_opt:
  mask_type: box
  mask_ratio: [0.4, 0.7]
  image_size: 64

ref_dir: figs/ffhq64-val

sampling:
  num_samples: 1
  num_steps: 200
  rho: 7
  lamb: 1200.
  xi: 0.
  no_grad: True
  num_queries: 100000
  mu: 0.05
  batch_size: 500

log:
  basedir: ffhq64-diffpir-inpaint
  progdir: prog
  tracking: False
