operator: 
  name: inpainting
  sigma_noise: 0.05      # measurement noise level

model: 
  sigma_min: 0.002
  sigma_max: 40.
  url: models/ffhq256.pkl
  device: cuda

mask_opt:
  mask_type: box
  mask_ratio: [0.4, 0.7]
  image_size: 256

ref_dir: figs/ffhq256-val

sampling:
  num_samples: 1
  num_steps: 1000
  rho: 7
  scale: 750.

log:
  basedir: dps256-inpaint
  progdir: prog
  tracking: False