operator: 
  name: inpainting
  sigma_noise: 0.05      # measurement noise level

model: 
  sigma_min: 0.002
  sigma_max: 40.
  url: https://nvlabs-fi-cdn.nvidia.com/edm/pretrained/edm-ffhq-64x64-uncond-vp.pkl
  device: cuda

mask_opt:
  mask_type: box
  mask_ratio: [0.4, 0.7]
  image_size: 64

ref_dir: figs/ffhq64-val

sampling:
  num_samples: 1
  num_steps: 350
  rho: 7
  scale: 750.

log:
  basedir: dps64-inpaint
  progdir: prog
  tracking: False