data:

model: 
  sigma_min: 0.002
  sigma_max: 80.
  url: models/ffhq256.pkl
  device: cuda
  img_size: 256

sampling:
  num_samples: 16
  num_steps: 500
  rho: 7

log:
  basedir: ffhq256-euler
  progdir: prog
  tracking: False