data:

model: 
  sigma_min: 0.002
  sigma_max: 60.
  url: models/imagenet256.pkl
  device: cuda
  img_size: 256

sampling:
  num_samples: 4
  num_steps: 50
  rho: 7

log:
  basedir: imagenet256-euler
  progdir: prog
  tracking: False