data:

model: 
  sigma_min: 0.002
  sigma_max: 80.
  url: https://nvlabs-fi-cdn.nvidia.com/edm/pretrained/edm-imagenet-64x64-cond-adm.pkl
  device: cuda
  img_size: 64

sampling:
  num_samples: 16
  num_steps: 256
  rho: 7

log:
  basedir: imagenet64-euler
  progdir: prog
  tracking: False